// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB66JeMcsPKSIGY3bycRuifwtZlykwNYqk',
    appId: '1:745496971204:web:d8cf52de9c97affd5c0691',
    messagingSenderId: '745496971204',
    projectId: 'vocab-28122025',
    authDomain: 'vocab-28122025.firebaseapp.com',
    storageBucket: 'vocab-28122025.firebasestorage.app',
    measurementId: 'G-V86J5LQ9XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBnBsXmn4Hzh1BJeLqgKqj8H40g04z1w4',
    appId: '1:745496971204:android:8cf1bb68cea702705c0691',
    messagingSenderId: '745496971204',
    projectId: 'vocab-28122025',
    storageBucket: 'vocab-28122025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Z68TQ41KQJcuOawq8QW3dWduy7eWoiQ',
    appId: '1:745496971204:ios:da3e8988414806755c0691',
    messagingSenderId: '745496971204',
    projectId: 'vocab-28122025',
    storageBucket: 'vocab-28122025.firebasestorage.app',
    iosBundleId: 'com.example.vocab',
  );
}
